apiVersion: v1
kind: Service
metadata:
  name: syslog-service
spec:
  type: ClusterIP
  selector:
    app: syslog-server
  ports:
  - port: 514
    targetPort: 514
    protocol: UDP


---
apiVersion: v1
kind: Service
metadata:
  name: "service-hive"
  namespace: "rsyslog"
spec:
  ports:
    - port: 514
      targetPort: 514
      protocol: TCP
  type: NodePort
  selector:
    app: "rsyslog"
